//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheWitcher.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clothes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clothes()
        {
            this.HeroClothes = new HashSet<HeroClothes>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ClothesType { get; set; }
        public Nullable<decimal> PriceOfBuy { get; set; }
        public Nullable<int> ClothesAccessLevel { get; set; }
        public Nullable<int> ClothesWeight { get; set; }
        public string Characteristics { get; set; }
        public string Colour { get; set; }
        public Nullable<int> CombatPower { get; set; }
    
        public virtual ClothesType ClothesType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HeroClothes> HeroClothes { get; set; }
    }
}
