//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheWitcher.DataAccess.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Heroes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Heroes()
        {
            this.HeroClothes = new HashSet<HeroClothes>();
            this.HeroInQuest = new HashSet<HeroInQuest>();
            this.HeroWeapon = new HashSet<HeroWeapon>();
        }
    
        public int Id { get; set; }
        public string HeroName { get; set; }
        public Nullable<decimal> HeroMoney { get; set; }
        public Nullable<int> HeroLevel { get; set; }
        public Nullable<bool> Playable { get; set; }
        public string HeroDescription { get; set; }
        public Nullable<int> AvailableWeight { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HeroClothes> HeroClothes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HeroInQuest> HeroInQuest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HeroWeapon> HeroWeapon { get; set; }
    }
}
