//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheWitcher.DataAccess.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeroWeapon
    {
        public int Id { get; set; }
        public Nullable<int> HeroId { get; set; }
        public Nullable<int> WeaponId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<decimal> PriceOfSell { get; set; }
    
        public virtual Heroes Heroes { get; set; }
        public virtual Weapons Weapons { get; set; }
    }
}
