//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheWitcher.DataAccess.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Quest()
        {
            this.HeroInQuest = new HashSet<HeroInQuest>();
        }
    
        public int Id { get; set; }
        public string QuestName { get; set; }
        public Nullable<decimal> Award { get; set; }
        public Nullable<System.TimeSpan> LeadTime { get; set; }
        public Nullable<int> AccessLevel { get; set; }
        public Nullable<int> Complexity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HeroInQuest> HeroInQuest { get; set; }
    }
}
